"""Add expense_type to BudgetModel

Revision ID: 425527d25b72
Revises: f61915e41e0d
Create Date: 2025-12-14 14:50:51.345575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '425527d25b72'
down_revision: Union[str, None] = 'f61915e41e0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_entries', sa.Column('expense_type', sa.String(), nullable=True))
    op.create_index(op.f('ix_tenants_created_at'), 'tenants', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_created_at'), table_name='tenants')
    op.drop_column('budget_entries', 'expense_type')
    # ### end Alembic commands ###
