"""Add settings column

Revision ID: f61915e41e0d
Revises: 6f63c4372b27
Create Date: 2025-12-07 11:23:47.369595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f61915e41e0d'
down_revision: Union[str, None] = '6f63c4372b27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_usage_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_tenant_id', sa.String(), nullable=False),
    sa.Column('original_created_at', sa.DateTime(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('session_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('total_transactions_logged', sa.Integer(), nullable=True),
    sa.Column('total_budget_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('feature_usage_summary', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tenants', sa.Column('settings', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'settings')
    op.drop_table('guest_usage_stats')
    # ### end Alembic commands ###
